name: AppInspect

on:
  push:
    paths:
      - 'packages/**'
      - '.github/workflows/*'

jobs:
  build:
    uses: splunk/splunk-3D-graph-network-topology-viz/.github/workflows/build.yml@master

  appinspect-cli:
    name: AppInspect CLI Validation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install splunk-appinspect
      
      - name: Run AppInspect
        run: |
          ls .
          app_id=$(cat splunk-*/app.manifest | jq -r '.info.id.name')
          cp ../README.md ${app_id}
          splunk-appinspect inspect ${app_id} --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`
        working-directory: ./packages

  appinspect-api:
    name: AppInspect API Validation
    needs: 
      - appinspect-cli
      - build
    runs-on: ubuntu-latest
    # Job not executed if branch is not master
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged_app

      - name: Move artifact to build/ folder
        run: |
          mkdir -p build
          app_package=$(ls -1 *gz | xargs basename)
          mv ${app_package} build/

      - name: Run AppInspect
        uses: splunk/appinspect-api-action@v3.0
        with:
          username: ${{ secrets.SPLUNKBASE_USERNAME }}
          password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_path: build/
          includedTags: "cloud"