name: build

on: workflow_call


jobs:
  build:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get App Info
        id: app
        run: |
          app_id=$(cat splunk-*/app.manifest | jq -r '.info.id.name')
          app_version=$(cat splunk-*/app.manifest | jq -r '.info.id.version')
          echo "name=${app_id}" >> $GITHUB_OUTPUT
          echo "version=${app_version}" >> $GITHUB_OUTPUT
        working-directory: ./packages

      - name: Bundle App Source
        run: |
          mkdir -p build
          tar -C packages -zcvf build/${{ steps.app.outputs.name }}-${{ steps.app.outputs.version }}.tgz ${{ steps.app.outputs.name }}/
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged_app
          path: build/*
