name: CI

on: 
  push:
    paths-ignore:
      - '.github/workflows/manual-release.yml'
      - '.github/workflows/tests.yml'

jobs:
  bundle-app:
    name: Bundle App
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.appinfo.outputs.app_name }}
      app_id: ${{ steps.appinfo.outputs.app_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Fetch and set app info
        id: appinfo
        run: |
          APP_ID=$(cat packages/splunk-*/app.manifest | jq -r '.info.id.name')
          echo "app_id=${APP_ID}" >> $GITHUB_OUTPUT
          APP_NAME=$(echo "$APP_ID" | tr _ - )
          echo "app_name=${APP_NAME}" >> $GITHUB_OUTPUT

      - name: Excluding images from README
        run: |
          sed -i '/^!/d' README.md

     - name: Bundle app source
        run: |
          mkdir dist
          cp README.md packages/splunk-*/
          cp AUTHORS.md packages/splunk-*/
          tar -zcvf dist/${{ steps.appinfo.outputs.app_name }}.tgz packages/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app_tgz
          path: dist/${{ steps.appinfo.outputs.app_name }}.tgz

  appinspect-cli:
    name: AppInspect CLI Validation
    needs: bundle-app
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install splunk-appinspect
      
      - name: Run AppInspect
        run: |
          splunk-appinspect inspect ${{ needs.bundle-app.outputs.app_id }} --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`
        working-directory: ./packages

  appinspect-api:
    name: AppInspect API Validation
    needs: 
      - bundle-app
      - appinspect-cli
    runs-on: ubuntu-latest
    # Job not executed if branch is not master
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AppInspect
        uses: splunk/appinspect-api-action@v3.0
        with:
          # filePath: ${{ needs.bundle-app.outputs.app_name }}.tgz
          username: ${{ secrets.SPLUNKBASE_USERNAME }}
          password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_path: packages/
          includedTags: cloud